import React, { useState } from 'react';
import { textService } from '../services/api';
import toast from 'react-hot-toast';
import { DocumentDuplicateIcon } from '@heroicons/react/24/outline';

const Detector = () => {
  const [text, setText] = useState('');
  const [result, setResult] = useState(null);
  const [loading, setLoading] = useState(false);
  const [charCount, setCharCount] = useState(0);

  const handleTextChange = (e) => {
    setText(e.target.value);
    setCharCount(e.target.value.length);
  };

  const handleDetect = async () => {
    if (text.length < 10) {
      toast.error('Please enter at least 10 characters');
      return;
    }

    setLoading(true);
    try {
      const response = await textService.detectAI(text);
      setResult(response);
      toast.success('Analysis complete!');
    } catch (error) {
      console.error('Detection failed');
    } finally {
      setLoading(false);
    }
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(text);
    toast.success('Copied!');
  };

  const handleClear = () => {
    setText('');
    setResult(null);
    setCharCount(0);
  };

  const getScoreColor = (score) => {
    if (score >= 70) return 'text-red-600';
    if (score >= 40) return 'text-yellow-600';
    return 'text-green-600';
  };

  return (
    <div className="max-w-4xl mx-auto space-y-8">
      <div className="text-center">
        <h1 className="text-3xl font-bold text-gray-900">AI Text Detector</h1>
        <p className="text-gray-600">Check if your text was generated by AI</p>
      </div>

      <div className="bg-white rounded-xl shadow-lg p-6">
        <textarea
          rows="8"
          className="input-field"
          placeholder="Enter text to analyze (minimum 10 characters)..."
          value={text}
          onChange={handleTextChange}
          disabled={loading}
        />
        
        <div className="flex justify-between items-center mt-2 text-sm">
          <span>{charCount} characters</span>
          <span className={charCount < 10 ? 'text-red-500' : 'text-green-500'}>
            {charCount < 10 ? 'Minimum 10 chars' : '✓ Ready'}
          </span>
        </div>

        <div className="flex space-x-4 mt-4">
          <button
            onClick={handleDetect}
            disabled={loading || text.length < 10}
            className="btn-primary flex-1"
          >
            {loading ? 'Analyzing...' : 'Detect AI Text'}
          </button>
          <button onClick={handleCopy} disabled={!text} className="btn-secondary">
            <DocumentDuplicateIcon className="h-5 w-5" />
          </button>
          <button onClick={handleClear} disabled={!text} className="btn-secondary">
            Clear
          </button>
        </div>
      </div>

      {result && (
        <div className="bg-white rounded-xl shadow-lg p-6">
          <h2 className="text-xl font-semibold mb-4">Results</h2>
          
          <div className="text-center mb-6">
            <div className={`text-5xl font-bold mb-2 ${getScoreColor(result.aiScore)}`}>
              {result.aiScore}%
            </div>
            <p className="text-gray-600">{result.message}</p>
          </div>

          <div className="border-t pt-4">
            <div className="flex justify-between items-center">
              <span className="text-gray-600">AI Probability</span>
              <span className={`font-semibold ${getScoreColor(result.aiScore)}`}>
                {result.aiScore}%
              </span>
            </div>
            <div className="flex justify-between items-center mt-2">
              <span className="text-gray-600">Human Probability</span>
              <span className="font-semibold text-green-600">
                {(100 - result.aiScore).toFixed(1)}%
              </span>
            </div>
          </div>

          <p className="text-xs text-gray-500 mt-4">
            Analyzed: {new Date(result.processedAt).toLocaleString()}
          </p>
        </div>
      )}
    </div>
  );
};

export default Detector;